### ISSUE TITLE
on new csv load

### ISSUE THREAD

**Issue by sy-be** [sy-bee/cgt-calculator#1]
```Traceback (most recent call last):
  File "main.py", line 64, in on_calculate_clicked
    self.calculator.calculate()
  File "/home/sy/src/cgt-calculator/lib/calculator.py", line 16, in calculate
    for name, group in self.df.groupby('Product'):
  File "/usr/lib/python3/dist-packages/pandas/core/generic.py", line 7884, in groupby
    return groupby(
  File "/usr/lib/python3/dist-packages/pandas/core/groupby/groupby.py", line 2522, in groupby
    return klass(obj, by, **kwds)
  File "/usr/lib/python3/dist-packages/pandas/core/groupby/groupby.py", line 384, in __init__
    grouper, exclusions, obj = _get_grouper(
  File "/usr/lib/python3/dist-packages/pandas/core/groupby/grouper.py", line 621, in _get_grouper
    raise KeyError(gpr)
KeyError: 'Product'
```

**Comment by sy-be** [comment]
works after relaunching
